import * as vscode from 'vscode';
import * as path from 'node:path';
import { ProviderId } from '../types';
const SECTION='vectra';
export interface AgentConfiguration{
  provider:ProviderId;model:string;localModelPath:string;localModelDirectory:string;llamaCppServerPath:string;llamaCppPort:number;llamaCppContextSize:number;llamaCppLoadTimeoutSeconds:number;llamaCppGpuLayers:string;llamaCppSplitMode:'none'|'layer'|'row'|'tensor';llamaCppCpuMoe:boolean;llamaCppNoMmap:boolean;llamaCppMmprojPath:string;llamaCppExtraArgs:string[];
  ollamaBaseUrl:string;openaiCompatibleBaseUrl:string;openaiBaseUrl:string;anthropicBaseUrl:string;geminiBaseUrl:string;maxAgentSteps:number;maxFileBytes:number;maxContextCharacters:number;excludeGlob:string;supportDeveloperUrl:string;showDiagnosticsInContext:boolean;allowSensitiveFiles:boolean;
}
export function getConfig():AgentConfiguration{const c=vscode.workspace.getConfiguration(SECTION);return{provider:c.get<ProviderId>('provider','llamaCpp'),model:c.get<string>('model','').trim(),localModelPath:c.get<string>('localModelPath','').trim(),localModelDirectory:c.get<string>('localModelDirectory','').trim(),llamaCppServerPath:c.get<string>('llamaCppServerPath','').trim(),llamaCppPort:c.get<number>('llamaCppPort',8080),llamaCppContextSize:c.get<number>('llamaCppContextSize',16384),llamaCppLoadTimeoutSeconds:c.get<number>('llamaCppLoadTimeoutSeconds',600),llamaCppGpuLayers:c.get<string>('llamaCppGpuLayers','auto').trim()||'auto',llamaCppSplitMode:c.get<AgentConfiguration['llamaCppSplitMode']>('llamaCppSplitMode','layer'),llamaCppCpuMoe:c.get<boolean>('llamaCppCpuMoe',false),llamaCppNoMmap:c.get<boolean>('llamaCppNoMmap',false),llamaCppMmprojPath:c.get<string>('llamaCppMmprojPath','').trim(),llamaCppExtraArgs:c.get<string[]>('llamaCppExtraArgs',[]),ollamaBaseUrl:trim(c.get<string>('ollamaBaseUrl','http://localhost:11434')),openaiCompatibleBaseUrl:trim(c.get<string>('openaiCompatibleBaseUrl','http://localhost:1234/v1')),openaiBaseUrl:trim(c.get<string>('openaiBaseUrl','https://api.openai.com/v1')),anthropicBaseUrl:trim(c.get<string>('anthropicBaseUrl','https://api.anthropic.com/v1')),geminiBaseUrl:trim(c.get<string>('geminiBaseUrl','https://generativelanguage.googleapis.com/v1beta')),maxAgentSteps:c.get<number>('maxAgentSteps',12),maxFileBytes:c.get<number>('maxFileBytes',1_000_000),maxContextCharacters:c.get<number>('maxContextCharacters',180_000),excludeGlob:c.get<string>('excludeGlob','**/{node_modules,.git,dist,build,out,.next,.venv,venv,__pycache__,coverage}/**'),supportDeveloperUrl:c.get<string>('supportDeveloperUrl','https://github.com/Laudarisd/vectra.git'),showDiagnosticsInContext:c.get<boolean>('showDiagnosticsInContext',true),allowSensitiveFiles:c.get<boolean>('allowSensitiveFiles',false)}}
export async function updateProvider(v:ProviderId){await vscode.workspace.getConfiguration(SECTION).update('provider',v,vscode.ConfigurationTarget.Global)}
export async function updateModel(v:string){await vscode.workspace.getConfiguration(SECTION).update('model',v,vscode.ConfigurationTarget.Global)}
export async function updateLocalModel(v:string){const c=vscode.workspace.getConfiguration(SECTION);await c.update('localModelPath',v,vscode.ConfigurationTarget.Global);await c.update('localModelDirectory',path.dirname(v),vscode.ConfigurationTarget.Global)}
export async function updateLlamaServerPath(v:string){await vscode.workspace.getConfiguration(SECTION).update('llamaCppServerPath',v,vscode.ConfigurationTarget.Global)}
export async function updateLlamaMmprojPath(v:string){await vscode.workspace.getConfiguration(SECTION).update('llamaCppMmprojPath',v,vscode.ConfigurationTarget.Global)}
function trim(v:string){return v.replace(/\/+$/,'')}
