import http from 'node:http';
import { readFile, stat, mkdtemp, writeFile, readdir, rm } from 'node:fs/promises';
import { createReadStream, existsSync } from 'node:fs';
import { extname, join, normalize, resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { tmpdir } from 'node:os';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { inflateSync } from 'node:zlib';
import { LocalLlamaManager } from './lib/local-llama.mjs';
import { extractPdfText as extractPdfTextRobust, extractDocumentText, artifactForRequest } from './lib/documents.mjs';
import { ChatHistoryStore } from './lib/history.mjs';
import { discoverLocalRuntimes, searchGgufModels } from './lib/local-discovery.mjs';
const execFileAsync=promisify(execFile);
const here=dirname(fileURLToPath(import.meta.url)); const publicRoot=existsSync(join(here,'dist'))?join(here,'dist'):join(here,'public'); const host=process.env.VECTRA_HOST||'127.0.0.1'; let port=Number(process.env.VECTRA_PORT||4173); const MAX_BODY=110*1024*1024; const localLlama=new LocalLlamaManager(); const history=new ChatHistoryStore();
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url||'/',`http://${req.headers.host||'localhost'}`);const pathname=url.pathname;if(pathname.startsWith('/api/'))assertApiRequest(req);if(pathname==='/api/chats'||pathname.startsWith('/api/chats/'))return await handleHistory(req,res,pathname,url);if(req.method==='POST'&&pathname==='/api/chat')return await handleChat(req,res);if(req.method==='POST'&&pathname==='/api/models')return await handleModels(req,res);if(req.method==='POST'&&pathname==='/api/attachments/inspect')return await handleAttachmentInspect(req,res);if(req.method==='GET'&&pathname==='/api/local/status')return json(res,200,localLlama.snapshot());if(req.method==='POST'&&pathname==='/api/local/discover'){assertLocalRuntimeAllowed();return json(res,200,{runtimes:await discoverRuntimes()})}if(req.method==='POST'&&pathname==='/api/local/search-models'){assertLocalRuntimeAllowed();return json(res,200,{models:await searchGgufModels(await readJson(req))})}if(req.method==='POST'&&pathname==='/api/local/choose-model'){assertLocalRuntimeAllowed();return json(res,200,await localLlama.chooseModel())}if(req.method==='POST'&&pathname==='/api/local/choose-mmproj'){assertLocalRuntimeAllowed();return json(res,200,await localLlama.chooseMmproj())}if(req.method==='POST'&&pathname==='/api/local/choose-server'){assertLocalRuntimeAllowed();return json(res,200,await localLlama.chooseServer())}if(req.method==='POST'&&pathname==='/api/local/start'){assertLocalRuntimeAllowed();return json(res,200,await localLlama.start(await readJson(req)))}if(req.method==='POST'&&pathname==='/api/local/stop'){assertLocalRuntimeAllowed();return json(res,200,await localLlama.stop())}if(req.method!=='GET'&&req.method!=='HEAD')return json(res,405,{error:'Method not allowed'});return await serveStatic(req,res)}catch(e){console.error('[Vectra Web]',e instanceof Error?e.message:e);return json(res,500,{error:e instanceof Error?e.message:String(e)})}});
listenWithFallback(port);
function listenWithFallback(candidate, remaining=20){port=candidate;const onListening=()=>{server.removeListener('error',onError);console.log(`Vectra Web: http://${host}:${candidate}`);console.log('Keys are accepted per request and never written to disk by this server.');console.log('Local GGUF loading is available when Vectra Web is bound to localhost.');};const onError=(error)=>{server.removeListener('listening',onListening);if(error?.code==='EADDRINUSE'&&remaining>0){console.warn(`Port ${candidate} is busy. Trying ${candidate+1}…`);setTimeout(()=>listenWithFallback(candidate+1,remaining-1),20);return;}console.error('Vectra Web failed to start:',error);process.exitCode=1;};server.once('error',onError);server.once('listening',onListening);server.listen(candidate,host);}
process.on('SIGINT',async()=>{await localLlama.stop().catch(()=>{});history.close();server.close(()=>process.exit(0))});
process.on('SIGTERM',async()=>{await localLlama.stop().catch(()=>{});history.close();server.close(()=>process.exit(0))});
function assertLocalRuntimeAllowed(){if(!['127.0.0.1','localhost','::1'].includes(host))throw new Error('Local GGUF file selection and llama-server launch are disabled when Vectra Web is not bound to localhost. Start with VECTRA_HOST=127.0.0.1.');}
function assertApiRequest(req){const origin=req.headers.origin;if(!origin)return;let parsed;try{parsed=new URL(origin)}catch{throw new Error('Invalid request origin.')}if(parsed.host!==req.headers.host)throw new Error('Cross-origin API requests are not allowed by Vectra Web.');}

async function handleHistory(req,res,pathname,url){
  if(req.method==='GET'&&pathname==='/api/chats')return json(res,200,{chats:history.list(url.searchParams.get('limit'))});
  if(req.method==='POST'&&pathname==='/api/chats')return json(res,201,history.save(await readJson(req)));
  const match=pathname.match(/^\/api\/chats\/([a-zA-Z0-9-]{8,80})$/);
  if(!match)return json(res,404,{error:'Chat not found'});
  const id=match[1];
  if(req.method==='GET'){const chat=history.get(id);return chat?json(res,200,chat):json(res,404,{error:'Chat not found'});}
  if(req.method==='PUT')return json(res,200,history.save({...await readJson(req),id}));
  if(req.method==='DELETE')return json(res,200,{deleted:history.delete(id)});
  return json(res,405,{error:'Method not allowed'});
}

async function handleChat(req,res){
  const b=await readJson(req);let{provider='openai',apiKey='',model='',baseUrl='',messages=[],attachments=[]}=b;
  if(provider==='localAuto'&&!baseUrl){const runtimes=await discoverRuntimes();const runtime=runtimes.find(item=>item.models.includes(model))||runtimes[0];if(!runtime)return json(res,400,{error:'No supported local model server was detected. Start Ollama, LM Studio, llama.cpp, vLLM, or another OpenAI-compatible runtime.'});baseUrl=runtime.baseUrl;model=model||runtime.models[0]}
  if(provider==='llamaCpp'){
    const local=localLlama.snapshot();
    if(local.status==='ready'&&local.running){const connection=localLlama.connection();baseUrl=connection.baseUrl;model=model||connection.modelId;apiKey=connection.apiKey}
    else if(!baseUrl)return json(res,400,{error:'No local llama.cpp model is running. Open Model, choose a GGUF file, and start it first.'});
  }
  if(!model)return json(res,400,{error:'Select or enter a model.'});
  if(!['llamaCpp','openaiCompatible','localAuto'].includes(provider)&&!apiKey)return json(res,400,{error:'API key is required for this provider.'});
  const safeMessages=Array.isArray(messages)?messages.slice(-30).map(m=>({role:m.role==='assistant'?'assistant':'user',content:String(m.content||'')})):[];
  const safeAttachments=await preprocessAttachments(Array.isArray(attachments)?attachments.slice(0,12).map(sanitizeAttachment):[],provider);
  let text=await callProvider(provider,{apiKey,model,baseUrl,messages:safeMessages,attachments:safeAttachments});
  if(hasUsableAttachmentContent(safeAttachments)&&looksLikeFalseAttachmentRefusal(text)){
    const retryMessages=[...safeMessages,{role:'user',content:'SYSTEM CORRECTION FROM VECTRA RUNTIME: The attached files have already been parsed and their actual content is included in this request. Answer the original user request using that content now. Do not ask the user to paste the file, and do not say you cannot access attachments.'}];
    text=await callProvider(provider,{apiKey,model,baseUrl,messages:retryMessages,attachments:safeAttachments});
  }
  const latestUser=[...safeMessages].reverse().find(m=>m.role==='user')?.content||'';
  const artifacts=artifactForRequest(latestUser,text,safeAttachments);
  return json(res,200,{text,artifacts,attachments:safeAttachments.map(a=>({name:a.name,kind:a.kind,mime:a.mime,parsedCharacters:(a.text||'').length}))});
}
async function handleAttachmentInspect(req,res){const body=await readJson(req);const provider=String(body.provider||'llamaCpp');const input=sanitizeAttachment(body.attachment||{});const parsed=await preprocessAttachments([input],provider);const primary=parsed[0]||input;return json(res,200,{name:primary.name,kind:primary.kind,mime:primary.mime,text:primary.text||'',parsedCharacters:(primary.text||'').length,visualPages:Math.max(0,parsed.length-1)})}
async function callProvider(provider,args){if(provider==='openai')return openAIChat(args);if(provider==='anthropic')return anthropicChat(args);if(provider==='gemini')return geminiChat(args);return compatibleChat({...args,baseUrl:args.baseUrl||'http://127.0.0.1:8080/v1'})}

async function handleModels(req,res){let{provider='openai',apiKey='',baseUrl=''}=await readJson(req);if(!['llamaCpp','openaiCompatible','localAuto'].includes(provider)&&!apiKey)return json(res,400,{error:'API key required.'});let models=[];let runtimes=[];if(provider==='openai'){const d=await fetchJson(`${trim(baseUrl||'https://api.openai.com/v1')}/models`,{headers:{Authorization:`Bearer ${apiKey}`}});models=(d.data||[]).map(x=>x.id).filter(Boolean).sort()}else if(provider==='anthropic'){const d=await fetchJson(`${trim(baseUrl||'https://api.anthropic.com/v1')}/models`,{headers:{'x-api-key':apiKey,'anthropic-version':'2023-06-01'}});models=(d.data||[]).map(x=>x.id).filter(Boolean)}else if(provider==='gemini'){const root=trim(baseUrl||'https://generativelanguage.googleapis.com/v1beta');const d=await fetchJson(`${root}/models`,{headers:{'x-goog-api-key':apiKey}});models=(d.models||[]).map(x=>String(x.name||'').replace(/^models\//,'')).filter(Boolean)}else if(provider==='llamaCpp'){const local=localLlama.snapshot();if(local.status==='ready'&&local.running)models=await localLlama.listModels();else if(baseUrl){const d=await fetchJson(`${trim(baseUrl)}/models`);models=(d.data||[]).map(x=>x.id).filter(Boolean)}else throw new Error('No local llama.cpp model is running. Open Model, choose and start a GGUF model first.')}else if(provider==='localAuto'){runtimes=await discoverRuntimes();models=[...new Set(runtimes.flatMap(runtime=>runtime.models))];}else{const d=await fetchJson(`${trim(baseUrl||'http://127.0.0.1:8080/v1')}/models`,{headers:apiKey?{Authorization:`Bearer ${apiKey}`}:{}});models=(d.data||[]).map(x=>x.id).filter(Boolean)}return json(res,200,{models,runtimes})}

async function discoverRuntimes(){const local=localLlama.snapshot();const extra=local.running&&local.status==='ready'?[{name:'Vectra llama.cpp',baseUrl:local.baseUrl,discoveryUrl:`${local.baseUrl}/models`,apiKey:localLlama.connection().apiKey}]:[];return discoverLocalRuntimes(extra)}

async function openAIChat({apiKey,model,baseUrl,messages,attachments}){const content=[{type:'input_text',text:transcript(messages)}];for(const f of attachments){if(f.kind==='text'||f.kind==='document')content.push({type:'input_text',text:`\n[Attachment: ${f.name}]\n${f.text}`});else if(f.mime.startsWith('image/')&&f.base64)content.push({type:'input_image',image_url:`data:${f.mime};base64,${f.base64}`,detail:'auto'});else if(f.base64)content.push({type:'input_file',filename:f.name,file_data:`data:${f.mime};base64,${f.base64}`});if(f.kind==='pdf'&&f.text)content.push({type:'input_text',text:`\n[Extracted PDF text fallback: ${f.name}]\n${f.text}`})}const d=await fetchJson(`${trim(baseUrl||'https://api.openai.com/v1')}/responses`,{method:'POST',headers:{Authorization:`Bearer ${apiKey}`,'Content-Type':'application/json'},body:JSON.stringify({model,instructions:systemPrompt(attachments),input:[{role:'user',content}]})});const parts=[];if(d.output_text)parts.push(d.output_text);for(const i of d.output||[])for(const p of i.content||[])if(p.text)parts.push(p.text);if(!parts.join('').trim())throw new Error('OpenAI returned no text output.');return parts.join('\n').trim()}
async function anthropicChat({apiKey,model,baseUrl,messages,attachments}){const last=messages.at(-1)?.content||'';const history=messages.slice(0,-1).map(m=>({role:m.role,content:m.content}));const content=[{type:'text',text:last||'Please analyze the attached files.'}];for(const f of attachments){if(f.kind==='text'||f.kind==='document')content.push({type:'text',text:`\n[Attachment: ${f.name}]\n${f.text}`});else if(f.mime.startsWith('image/')&&f.base64)content.push({type:'image',source:{type:'base64',media_type:f.mime,data:f.base64}});else if(f.mime==='application/pdf'&&f.base64)content.push({type:'document',source:{type:'base64',media_type:f.mime,data:f.base64}});else if(f.text)content.push({type:'text',text:`\n[Extracted attachment: ${f.name}]\n${f.text}`})}const d=await fetchJson(`${trim(baseUrl||'https://api.anthropic.com/v1')}/messages`,{method:'POST',headers:{'x-api-key':apiKey,'anthropic-version':'2023-06-01','Content-Type':'application/json'},body:JSON.stringify({model,max_tokens:8192,system:systemPrompt(attachments),messages:[...history,{role:'user',content}]})});const text=(d.content||[]).filter(p=>p.type==='text').map(p=>p.text).join('\n').trim();if(!text)throw new Error('Anthropic returned no text output.');return text}
async function geminiChat({apiKey,model,baseUrl,messages,attachments}){const parts=[{text:transcript(messages)}];for(const f of attachments){if(f.kind==='text'||f.kind==='document')parts.push({text:`\n[Attachment: ${f.name}]\n${f.text}`});else if(f.base64)parts.push({inline_data:{mime_type:f.mime||'application/octet-stream',data:f.base64}});else if(f.text)parts.push({text:`\n[Attachment: ${f.name}]\n${f.text}`})}const root=trim(baseUrl||'https://generativelanguage.googleapis.com/v1beta');const d=await fetchJson(`${root}/models/${encodeURIComponent(model)}:generateContent`,{method:'POST',headers:{'x-goog-api-key':apiKey,'Content-Type':'application/json'},body:JSON.stringify({system_instruction:{parts:[{text:systemPrompt(attachments)}]},contents:[{role:'user',parts}]})});const text=(d.candidates||[]).flatMap(c=>c.content?.parts||[]).map(p=>p.text||'').join('\n').trim();if(!text)throw new Error('Gemini returned no text output.');return text}
async function compatibleChat({apiKey,model,baseUrl,messages,attachments}){const content=[{type:'text',text:messages.at(-1)?.content||'Please analyze the attached files.'}];for(const f of attachments){if((f.kind==='text'||f.kind==='pdf'||f.kind==='document')&&f.text)content.push({type:'text',text:`\n[Attachment: ${f.name}]\n${f.text}`});if(f.mime.startsWith('image/')&&f.base64)content.push({type:'image_url',image_url:{url:`data:${f.mime};base64,${f.base64}`}})}const history=messages.slice(0,-1).map(m=>({role:m.role,content:m.content}));const d=await fetchJson(`${trim(baseUrl)}/chat/completions`,{method:'POST',headers:{'Content-Type':'application/json',...(apiKey?{Authorization:`Bearer ${apiKey}`}:{})},body:JSON.stringify({model,messages:[{role:'system',content:systemPrompt(attachments)},...history,{role:'user',content}],temperature:.2})});const text=d.choices?.[0]?.message?.content?.trim();if(!text)throw new Error('Model endpoint returned no text output.');return text}

async function preprocessAttachments(files,provider){const out=[];for(const f of files){const lower=f.name.toLowerCase();if(f.mime==='application/pdf'&&f.base64){if(!f.text)f.text=(await extractPdfTextRobust(Buffer.from(f.base64,'base64'))).slice(0,2_000_000);f.kind='pdf';out.push(f);if((f.text||'').length<1500&&['llamaCpp','openAICompatible','openaiCompatible','localAuto'].includes(provider)){const pages=await renderPdfPages(f).catch(()=>[]);out.push(...pages)}}else if(/\.(doc|docx|pptx|xlsx|rtf)$/i.test(lower)&&f.base64){f.kind='document';if(!f.text)f.text=(await extractDocumentText(f.name,Buffer.from(f.base64,'base64'))).slice(0,2_000_000);out.push(f)}else out.push(f)}return out}

async function renderPdfPages(file){const dir=await mkdtemp(join(tmpdir(),'vectra-web-'));try{const pdf=join(dir,'doc.pdf');await writeFile(pdf,Buffer.from(file.base64,'base64'));await execFileAsync('pdftoppm',['-png','-f','1','-l','6','-r','120',pdf,join(dir,'page')],{timeout:60000,maxBuffer:2_000_000});const names=(await readdir(dir)).filter(n=>/^page-\d+\.png$/.test(n)).sort();const pages=[];for(const n of names){const b=await readFile(join(dir,n));pages.push({name:`${file.name} · ${n.replace('page-','page ').replace('.png','')}`,mime:'image/png',size:b.length,kind:'image',text:'',base64:b.toString('base64')})}return pages}finally{await rm(dir,{recursive:true,force:true}).catch(()=>{})}}
function extractPdfText(bytes){const latin=bytes.toString('latin1');const chunks=[];collect(latin,chunks);const r=/<<(.*?)>>\s*stream\r?\n([\s\S]*?)\r?\nendstream/g;let m;while((m=r.exec(latin))){if(/\/FlateDecode\b/.test(m[1])){try{collect(inflateSync(Buffer.from(m[2],'latin1')).toString('latin1'),chunks)}catch{}}else collect(m[2],chunks)}return chunks.join('\n').replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F]/g,'').replace(/\n{4,}/g,'\n\n\n').trim()}
function collect(src,out){let m;const lit=/\(((?:\\.|[^\\)])*)\)\s*(?:Tj|'|")/g;while((m=lit.exec(src)))out.push(m[1].replace(/\\([nrt()\\])/g,(_x,c)=>({n:'\n',r:'\r',t:'\t','(':'(',')':')','\\':'\\'}[c]||c)));const arr=/\[((?:.|\n|\r)*?)\]\s*TJ/g;while((m=arr.exec(src))){const p=[];const q=/\(((?:\\.|[^\\)])*)\)/g;let x;while((x=q.exec(m[1])))p.push(x[1]);if(p.length)out.push(p.join(''))}}
function systemPrompt(attachments=[]){const manifest=attachments.length?attachments.map(a=>`${a.name}: ${a.kind}, parsedText=${(a.text||'').length} chars${a.mime.startsWith('image/')?', image bytes provided':''}`).join('; '):'none';return`You are Vectra, a precise professional AI assistant with a local runtime that can parse uploaded files and generate downloadable files. ATTACHMENT MANIFEST: ${manifest}. If parsedText is greater than 0, you HAVE the file's extracted content in the request and must use it. Never tell the user to paste a PDF/DOCX/PPTX/XLSX that Vectra already parsed. If image bytes are provided to a vision-capable model, inspect them. A text-only local model may lack visual understanding, but that does not prevent it from reading extracted PDF/Office text. If the user asks to create/generate/export a PDF, DOCX, text, code, JSON, CSV, HTML or similar file, provide the exact final content; the Vectra runtime creates the downloadable artifact. Never claim Vectra cannot create/download files.`}
// Any real extracted text counts. A short document is still content the model
// has, so a refusal that claims otherwise is false and worth one correction.
function hasUsableAttachmentContent(files){return files.some(f=>(f.text||'').trim().length>0||f.mime?.startsWith('image/'))}
function looksLikeFalseAttachmentRefusal(text){const v=String(text||'').toLowerCase();return[/cannot (?:directly )?(?:access|view|open|read)/,/don't have (?:the )?(?:ability|capability) to (?:access|view|open|read)/,/paste (?:the )?text/,/copy and paste/,/share the text/,/cannot generate or send files/,/don't have (?:a )?file-sharing/].some(r=>r.test(v))}
function transcript(messages){return messages.map(m=>`${m.role==='assistant'?'ASSISTANT':'USER'}: ${m.content}`).join('\n\n')||'USER: Please analyze the attached files.'}
function sanitizeAttachment(f){return{name:String(f?.name||'attachment').slice(0,240),mime:String(f?.mime||'application/octet-stream').slice(0,120),size:Number(f?.size||0),kind:['text','pdf','image','document'].includes(f?.kind)?f.kind:'binary',text:typeof f?.text==='string'?f.text.slice(0,2_000_000):'',base64:typeof f?.base64==='string'?f.base64.slice(0,48_000_000):''}}
async function fetchJson(url,init={}){const r=await fetch(url,init);const raw=await r.text();let d;try{d=raw?JSON.parse(raw):{}}catch{d={raw}}if(!r.ok)throw new Error(`HTTP ${r.status}: ${typeof d==='object'?JSON.stringify(d).slice(0,3000):raw.slice(0,3000)}`);return d}
async function readJson(req){let total=0;const chunks=[];for await(const chunk of req){total+=chunk.length;if(total>MAX_BODY)throw new Error('Request body is too large.');chunks.push(chunk)}const raw=Buffer.concat(chunks).toString('utf8');return raw?JSON.parse(raw):{}}
async function serveStatic(req,res){let pathname=new URL(req.url||'/',`http://${req.headers.host||'localhost'}`).pathname;if(pathname==='/')pathname='/index.html';const requested=normalize(decodeURIComponent(pathname)).replace(/^(\.\.[/\\])+/, '');const full=resolve(publicRoot,`.${requested}`);if(!full.startsWith(resolve(publicRoot)))return json(res,403,{error:'Forbidden'});try{const s=await stat(full);if(!s.isFile())return json(res,404,{error:'Not found'});res.writeHead(200,{'Content-Type':mime(extname(full)),'Content-Length':s.size,'Cache-Control':'no-store'});if(req.method==='HEAD')return res.end();createReadStream(full).pipe(res)}catch{return json(res,404,{error:'Not found'})}}
function mime(ext){return({'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.json':'application/json; charset=utf-8'})[ext]||'application/octet-stream'}
function json(res,status,data){const body=JSON.stringify(data);res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Content-Length':Buffer.byteLength(body),'Cache-Control':'no-store'});res.end(body)}
function trim(v){return String(v||'').replace(/\/+$/,'')}
