(function(){
  const vscode=acquireVsCodeApi(); const saved=vscode.getState()||{}; let mode=saved.mode||'agent'; let activityText='Analyzing…';
  let state={messages:[],proposals:[],attachments:[],busy:false,provider:'llamaCpp',model:'',localModelName:'',localModelRunning:false,visionEnabled:false,hasKey:true,isLocal:true,workspaceTrusted:true};
  const $=(id)=>document.getElementById(id); const els={messages:$('messages'),proposals:$('proposals'),attachments:$('attachments'),prompt:$('prompt'),send:$('sendButton'),stop:$('stopButton'),attach:$('attachButton'),clear:$('clearButton'),api:$('apiKeyButton'),local:$('localModelButton'),test:$('testButton'),settings:$('settingsButton'),dialog:$('settingsDialog'),runtime:$('runtimeInfo'),capability:$('capabilityInfo'),advanced:$('advancedSettingsButton'),support:$('supportButton')};
  document.querySelectorAll('.mode').forEach(b=>b.addEventListener('click',()=>{mode=b.dataset.mode;vscode.setState({mode});renderModes();updatePlaceholder();}));
  els.send.addEventListener('click',send); els.stop.addEventListener('click',()=>vscode.postMessage({type:'stop'})); els.attach.addEventListener('click',()=>vscode.postMessage({type:'attachFiles'})); els.clear.addEventListener('click',()=>vscode.postMessage({type:'clearChat'}));
  els.api.addEventListener('click',()=>vscode.postMessage({type:'setApiKey'})); els.local.addEventListener('click',()=>vscode.postMessage({type:'selectLocalModel'})); els.test.addEventListener('click',()=>vscode.postMessage({type:'testConnection'}));
  els.settings.addEventListener('click',()=>{renderSettings();els.dialog.showModal();}); els.advanced.addEventListener('click',()=>vscode.postMessage({type:'openSettings'})); els.support.addEventListener('click',()=>vscode.postMessage({type:'supportDeveloper'}));
  els.prompt.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();send();}});
  window.addEventListener('message',event=>{const m=event.data||{};if(m.type==='state'){state={...state,...m};if(!state.busy)activityText='Analyzing…';renderAll();}else if(m.type==='progress'){activityText=cleanActivity(m.message);renderMessages();}else if(m.type==='error'){activityText='Error';renderMessages();}});
  function send(){const text=els.prompt.value.trim();if(!text||state.busy||!state.workspaceTrusted)return;activityText='Analyzing…';vscode.postMessage({type:'send',text,mode});els.prompt.value='';}
  function renderAll(){renderModes();renderConnections();renderMessages();renderAttachments();renderProposals();renderComposer();renderSettings();updatePlaceholder();}
  function renderModes(){document.querySelectorAll('.mode').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));}
  function renderConnections(){const provider=providerLabel(state.provider);els.api.textContent=state.isLocal?'API Key':`API · ${shortName(state.model||provider,18)}`;els.local.textContent=state.localModelName?`Local · ${shortName(state.localModelName,17)}`:'Local Model';els.local.classList.toggle('active-connection',state.provider==='llamaCpp');els.api.classList.toggle('active-connection',!state.isLocal);els.api.classList.toggle('warning',!state.isLocal&&!state.hasKey);els.test.disabled=state.busy;}
  function renderMessages(){els.messages.replaceChildren();if(!state.messages.length&&!state.busy){const empty=document.createElement('div');empty.className='empty-state';empty.innerHTML='<div class="empty-title">Vectra</div><div>Ask about code, create or edit files, parse PDF/DOCX, attach images, or run approved tools in Agent mode.</div>';els.messages.appendChild(empty);}for(const m of state.messages){const card=document.createElement('article');card.className=`message ${m.role}`;const meta=document.createElement('div');meta.className='message-meta';meta.textContent=m.role==='assistant'?'Vectra':'You';const content=document.createElement('div');content.className='message-content';content.textContent=m.content;card.append(meta,content);if(m.attachments?.length){const row=document.createElement('div');row.className='message-attachments';for(const a of m.attachments){const chip=document.createElement('span');chip.className='attachment-readonly';chip.textContent=`${iconFor(a.kind)} ${a.name}`;row.appendChild(chip);}card.appendChild(row);}els.messages.appendChild(card);}if(state.busy){const card=document.createElement('article');card.className='message assistant activity-message';const meta=document.createElement('div');meta.className='message-meta';meta.textContent='Vectra';const line=document.createElement('div');line.className='activity-line';line.innerHTML='<span class="activity-spinner"></span><span></span>';line.lastElementChild.textContent=activityText;card.append(meta,line);els.messages.appendChild(card);}requestAnimationFrame(()=>{els.messages.scrollTop=els.messages.scrollHeight});}
  function renderAttachments(){els.attachments.replaceChildren();for(const a of state.attachments||[]){const chip=document.createElement('div');chip.className='attachment-chip';const label=document.createElement('span');label.textContent=`${iconFor(a.kind)} ${a.name} · ${formatSize(a.size)}`;const x=document.createElement('button');x.textContent='×';x.title='Remove';x.addEventListener('click',()=>vscode.postMessage({type:'removeAttachment',id:a.id}));chip.append(label,x);els.attachments.appendChild(chip);}}
  function renderProposals(){els.proposals.replaceChildren();const pending=state.proposals.filter(p=>p.status==='pending');if(!state.proposals.length)return;const header=document.createElement('div');header.className='proposal-section-header';const title=document.createElement('strong');title.textContent='Proposed changes';header.appendChild(title);if(pending.length>1){const actions=document.createElement('div');actions.className='proposal-batch-actions';actions.append(button('Accept all','primary small',()=>vscode.postMessage({type:'acceptAll'})),button('Reject all','secondary small',()=>vscode.postMessage({type:'rejectAll'})));header.appendChild(actions);}els.proposals.appendChild(header);for(const p of state.proposals){const card=document.createElement('article');card.className=`proposal ${p.status}`;const top=document.createElement('div');top.className='proposal-top';const fp=document.createElement('div');fp.className='proposal-path';fp.textContent=p.path;const badge=document.createElement('span');badge.className=`badge ${p.kind}`;badge.textContent=`${p.kind} · ${p.status}`;top.append(fp,badge);const reason=document.createElement('div');reason.className='proposal-reason';reason.textContent=p.reason||'Vectra-proposed change';const actions=document.createElement('div');actions.className='proposal-actions';actions.appendChild(button('View diff','secondary',()=>vscode.postMessage({type:'showDiff',id:p.id})));if(p.status==='pending')actions.append(button('Accept','primary',()=>vscode.postMessage({type:'accept',id:p.id})),button('Reject','danger-outline',()=>vscode.postMessage({type:'reject',id:p.id})));card.append(top,reason,actions);els.proposals.appendChild(card);}if(!pending.length)els.proposals.appendChild(button('Clear reviewed changes','secondary wide',()=>vscode.postMessage({type:'clearCompleted'})));}
  function renderComposer(){els.prompt.disabled=state.busy||!state.workspaceTrusted;els.attach.disabled=state.busy||!state.workspaceTrusted;els.send.classList.toggle('hidden',state.busy);els.send.disabled=!state.workspaceTrusted;els.stop.classList.toggle('hidden',!state.busy);}
  function renderSettings(){if(!els.runtime)return;const status=state.provider==='llamaCpp'?(state.localModelRunning?'Ready':'Stopped'):(state.hasKey?'Configured':'API key required');els.runtime.replaceChildren(row('Status',status),row('Provider',providerLabel(state.provider)),row('Model',state.localModelName||state.model||'Not selected'),row('Workspace',state.workspaceTrusted?'Trusted':'Restricted'));const vision=state.visionEnabled?'Vision enabled: images and visual PDF pages can be analyzed with the selected VLM/projector.':'Text/document mode: code, text files, extracted PDF text and Word documents are supported. Images, scans and visual PDF pages require a vision-capable GGUF with its matching mmproj.';els.capability.textContent=vision;}
  function row(k,v){const r=document.createElement('div');r.className='runtime-row';const a=document.createElement('span');a.textContent=k;const b=document.createElement('strong');b.textContent=v;r.append(a,b);return r;}
  function updatePlaceholder(){els.prompt.placeholder=mode==='agent'?'Tell Vectra what to build, edit, create, delete, run, or test…':mode==='ask'?'Ask about this repository or attach PDF, Word, code, or images…':'Ask Vectra to explain the exact selected code…';}
  function button(label,cls,handler){const e=document.createElement('button');e.className=cls;e.textContent=label;e.addEventListener('click',handler);return e;}
  function providerLabel(p){return({llamaCpp:'Local llama.cpp',ollama:'Ollama',openai:'OpenAI',anthropic:'Anthropic',gemini:'Gemini',openaiCompatible:'OpenAI-compatible'})[p]||p;}
  function shortName(v,n){return String(v).length>n?`${String(v).slice(0,n-1)}…`:String(v);}
  function formatSize(n){if(n<1024)return`${n} B`;if(n<1048576)return`${(n/1024).toFixed(1)} KB`;return`${(n/1048576).toFixed(1)} MB`;}
  function iconFor(k){return k==='pdf'?'PDF':k==='document'?'DOC':k==='image'?'IMG':k==='text'?'FILE':'BIN';}
  function cleanActivity(value){const v=String(value||'').trim();if(!v)return'Analyzing…';if(/agent step/i.test(v))return'Analyzing…';return v.length>90?`${v.slice(0,87)}…`:v;}
  renderModes();updatePlaceholder();vscode.postMessage({type:'ready'});
})();
